export default {
  'kind': "<<Kind>>",
  'subkind': "<<Subkind>>",
  'phase': "<<Phase>>",
  'role': "<<Role>>",
  'collective': "<<Collective>>",
  'quantity': "<<Quantity>>",
  'relator': "<<Relator>>",
  'category': "<<Category>>",
  'mixin': "<<Mixin>>",
  'phasemixin': "<<PhaseMixin>>",
  'rolemixin': "<<RoleMixin>>",
  'mode': "<<Mode>>",
  'quality': "<<Quality>>",
};